package com.sahan.csd63.model;

import javax.persistence.*;

@Entity(name="tbl_post")
public class Post {

    @Id //primary key for db table.....
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String caption;
    private String description;
    @Column(insertable = false,updatable = false) private String time;  // has to be Auto generated by DB for time
    private int flight_code;

    private String imgpath;

    public Post() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCaption() {
        return caption;
    }

    public void setCaption(String caption) {
        this.caption = caption;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public int getFlight_code() {
        return flight_code;
    }

    public void setFlight_code(int flight_code) {
        this.flight_code = flight_code;
    }

    public String getImgpath() {
        return imgpath;
    }

    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }





}
